package theme

import "github.com/charmbracelet/lipgloss"

var ThemeNames = []string{
	"default", "light", "dracula", "nord", "monokai", "gruvbox", "catppuccin", "rainbow",
}

var Themes = map[string]Theme{
	"default": {
		Name:   "default",
		BG:     lipgloss.Color("#323437"),
		FG:     lipgloss.Color("#d1d0c5"),
		Main:   lipgloss.Color("#e2b714"),
		Sub:    lipgloss.Color("#646669"),
		SubAlt: lipgloss.Color("#2c2e31"),
		PieceI: lipgloss.Color("#00b8d4"),
		PieceO: lipgloss.Color("#ffd600"),
		PieceT: lipgloss.Color("#aa00ff"),
		PieceS: lipgloss.Color("#00c853"),
		PieceZ: lipgloss.Color("#ff1744"),
		PieceJ: lipgloss.Color("#2979ff"),
		PieceL: lipgloss.Color("#ff9100"),
		Ghost:  lipgloss.Color("#4a4a4a"),
		Grid:   lipgloss.Color("#3a3c3f"),
	},
	"light": {
		Name:   "light",
		BG:     lipgloss.Color("#f5f5f5"),
		FG:     lipgloss.Color("#333333"),
		Main:   lipgloss.Color("#d4a017"),
		Sub:    lipgloss.Color("#999999"),
		SubAlt: lipgloss.Color("#e0e0e0"),
		PieceI: lipgloss.Color("#0097a7"),
		PieceO: lipgloss.Color("#f9a825"),
		PieceT: lipgloss.Color("#7b1fa2"),
		PieceS: lipgloss.Color("#2e7d32"),
		PieceZ: lipgloss.Color("#c62828"),
		PieceJ: lipgloss.Color("#1565c0"),
		PieceL: lipgloss.Color("#ef6c00"),
		Ghost:  lipgloss.Color("#cccccc"),
		Grid:   lipgloss.Color("#e8e8e8"),
	},
	"dracula": {
		Name:   "dracula",
		BG:     lipgloss.Color("#282a36"),
		FG:     lipgloss.Color("#f8f8f2"),
		Main:   lipgloss.Color("#bd93f9"),
		Sub:    lipgloss.Color("#6272a4"),
		SubAlt: lipgloss.Color("#21222c"),
		PieceI: lipgloss.Color("#8be9fd"),
		PieceO: lipgloss.Color("#f1fa8c"),
		PieceT: lipgloss.Color("#bd93f9"),
		PieceS: lipgloss.Color("#50fa7b"),
		PieceZ: lipgloss.Color("#ff5555"),
		PieceJ: lipgloss.Color("#6272a4"),
		PieceL: lipgloss.Color("#ffb86c"),
		Ghost:  lipgloss.Color("#44475a"),
		Grid:   lipgloss.Color("#343746"),
	},
	"nord": {
		Name:   "nord",
		BG:     lipgloss.Color("#2e3440"),
		FG:     lipgloss.Color("#eceff4"),
		Main:   lipgloss.Color("#88c0d0"),
		Sub:    lipgloss.Color("#4c566a"),
		SubAlt: lipgloss.Color("#272c36"),
		PieceI: lipgloss.Color("#88c0d0"),
		PieceO: lipgloss.Color("#ebcb8b"),
		PieceT: lipgloss.Color("#b48ead"),
		PieceS: lipgloss.Color("#a3be8c"),
		PieceZ: lipgloss.Color("#bf616a"),
		PieceJ: lipgloss.Color("#5e81ac"),
		PieceL: lipgloss.Color("#d08770"),
		Ghost:  lipgloss.Color("#3b4252"),
		Grid:   lipgloss.Color("#353b49"),
	},
	"monokai": {
		Name:   "monokai",
		BG:     lipgloss.Color("#272822"),
		FG:     lipgloss.Color("#f8f8f2"),
		Main:   lipgloss.Color("#f92672"),
		Sub:    lipgloss.Color("#75715e"),
		SubAlt: lipgloss.Color("#1e1f1c"),
		PieceI: lipgloss.Color("#66d9ef"),
		PieceO: lipgloss.Color("#e6db74"),
		PieceT: lipgloss.Color("#ae81ff"),
		PieceS: lipgloss.Color("#a6e22e"),
		PieceZ: lipgloss.Color("#f92672"),
		PieceJ: lipgloss.Color("#66d9ef"),
		PieceL: lipgloss.Color("#fd971f"),
		Ghost:  lipgloss.Color("#3e3d32"),
		Grid:   lipgloss.Color("#33342b"),
	},
	"gruvbox": {
		Name:   "gruvbox",
		BG:     lipgloss.Color("#282828"),
		FG:     lipgloss.Color("#ebdbb2"),
		Main:   lipgloss.Color("#fabd2f"),
		Sub:    lipgloss.Color("#665c54"),
		SubAlt: lipgloss.Color("#1d2021"),
		PieceI: lipgloss.Color("#83a598"),
		PieceO: lipgloss.Color("#fabd2f"),
		PieceT: lipgloss.Color("#d3869b"),
		PieceS: lipgloss.Color("#b8bb26"),
		PieceZ: lipgloss.Color("#fb4934"),
		PieceJ: lipgloss.Color("#458588"),
		PieceL: lipgloss.Color("#fe8019"),
		Ghost:  lipgloss.Color("#3c3836"),
		Grid:   lipgloss.Color("#32302f"),
	},
	"catppuccin": {
		Name:   "catppuccin",
		BG:     lipgloss.Color("#1e1e2e"),
		FG:     lipgloss.Color("#cdd6f4"),
		Main:   lipgloss.Color("#cba6f7"),
		Sub:    lipgloss.Color("#585b70"),
		SubAlt: lipgloss.Color("#181825"),
		PieceI: lipgloss.Color("#89dceb"),
		PieceO: lipgloss.Color("#f9e2af"),
		PieceT: lipgloss.Color("#cba6f7"),
		PieceS: lipgloss.Color("#a6e3a1"),
		PieceZ: lipgloss.Color("#f38ba8"),
		PieceJ: lipgloss.Color("#89b4fa"),
		PieceL: lipgloss.Color("#fab387"),
		Ghost:  lipgloss.Color("#313244"),
		Grid:   lipgloss.Color("#28283d"),
	},
	"rainbow": {
		Name:   "rainbow",
		BG:     lipgloss.Color("#1a1a2e"),
		FG:     lipgloss.Color("#eaeaea"),
		Main:   lipgloss.Color("#e94560"),
		Sub:    lipgloss.Color("#535373"),
		SubAlt: lipgloss.Color("#16163a"),
		PieceI: lipgloss.Color("#ff0000"),
		PieceO: lipgloss.Color("#ff8800"),
		PieceT: lipgloss.Color("#ffff00"),
		PieceS: lipgloss.Color("#00ff00"),
		PieceZ: lipgloss.Color("#0000ff"),
		PieceJ: lipgloss.Color("#4b0082"),
		PieceL: lipgloss.Color("#ee82ee"),
		Ghost:  lipgloss.Color("#2a2a4a"),
		Grid:   lipgloss.Color("#222244"),
	},
}

// GetTheme returns a theme by name, falling back to "default".
func GetTheme(name string) Theme {
	if t, ok := Themes[name]; ok {
		return t
	}
	return Themes["default"]
}
